#! /bin/bash

# Usage: $prog_name <interface> <action>
[ $# -ge 2 ] || exit 0

case "$2" in
    'pre-up'|'pre-down') ;;
    *) exit 0    ;;
esac

# Make sure we called as symlink in pre-{up,down}.d/
[ -z "${0##*/$2.d/*}" ] || exit 1

if [ "$2" = 'pre-up' ]; then
    CONFIG="/etc/sysconfig/network-scripts/ifcfg-$1"
    if [ -r "$CONFIG" ]; then
        eval $(
            # Source in subshell to not pollute environment
            if . "$CONFIG" >/dev/null 2>&1; then
                echo "GROUP='${GROUP-}'"
            fi
        )
    fi
    [ -n "${GROUP-}" ] || exit 0
else
    GROUP='default'
fi

exec ip link set dev "$1" group "$GROUP"
