#! /bin/bash

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=$1
need_config "$CONFIG"
source_config

ip link add dev "$DEVICE" type dummy

/etc/sysconfig/network-scripts/ifup-eth "$CONFIG" "$2"
